### ISSUE TITLE
Nlp based project structure [folder-layout]

### ISSUE THREAD

**Issue by masepehr** [drivendata/cookiecutter-data-science#100]
hi , i am new in cookiecutter ....
I want to use this template as base template for text classification project. I have preprocessing module. where should i put this module,in make_dataset, there is no need to download any data , i have my dataset.should DATABASE_URL variable in .env point to /data/raw folder?? in the other hand, i create featuress in preprocessing module and extract LDA based and tf-idf based feature from raw data  ,so should this be in feature folder ? i am confusing is this structure good for my project or not?

**Comment by pjbull** [comment]
Hi @masepehr, I'm closing this issue since it is a support request, not an issue with the software.

That said, here's what I'd recommend:
 - Feel free to remove `make_dataset.py` if you don't need an automated way to acquire the data.
 - I'd put the preprocessing code in `src/features/preprocess.py`
 - Sounds like you're using flat files, not a database for this project so you can ignore `DATABASE_URL`
 - I'd put the raw data in `data/raw`
 - I'd use the `preprocess.py` script to take the raw data from `data/raw` as input and output the tf-idf matrix to a file that lives in `data/processed`

Hope that helps!
