### ISSUE TITLE
The need for a data/queries?

### ISSUE THREAD

**Issue by GuiMarthe** [drivendata/cookiecutter-data-science#137]
Throughout my DS career I've always worked with DB connections and structured parameterized SQL queries. I also like to place them in a dedicated folder, and have been placing them in the `data/raw` directory (which I think is wrong given the cookiecutter philosophy). 

Also, in my work environment I keep a dedicated connections place (either ENV vars, or directory or text file). But it would be nice to have some where to place those connection configs in  a project specific manner. 

Does it make sense to have such structure? To prompt the user in the same fashion as the aws S3 and profile ? If so, what is the best way to do it?

**Comment by pjbull** [comment]
Hm, good questions.

If I'm writing queries with SQL I just put `.sql` files in the `src` folder. If I also include Python code as well, they usually go in `src/queries`. If those queries write out data, I would save that in `data/interim` or `data/processed`.

For connections, we generally use a `.env` file in the root directory that is _not included_ in source control since these often contain secrets that should be kept private. Then, if we need that string in Python, [we use this package](https://github.com/theskumar/python-dotenv). If you need those vars in scripts, you can `source` the `.env` file.

**Comment by wolfhoundjesse** [comment]
Think this goes back to the front page philosophy, _nothing here is binding_.

**Comment by isms** [comment]
Great question but closing as non-actionable now that there has been some time for public consideration.
