### ISSUE TITLE
Dependency errors with docutils and requirement file.

### ISSUE THREAD

**Issue by gus-morales** [drivendata/cookiecutter-data-science#198]
After creating the project with `cookiecutter` and installing the requirements when creating the environment, I get:

```
ERROR: botocore 1.15.0 has requirement docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible.
ERROR: awscli 1.18.0 has requirement docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible.

```

Both go away when I force docutils==0.15 in the requirements.txt file. Is there a way to fix this properly (i.e. without altering the cookiecutter source)?

**Comment by pjbull** [comment]
Since this is a project template, we're not going to pin library versions in the source.

There's no real fix for this except to remove `awscli` from the requirements or add the specific `docutils`, and it doesn't make sense for us to do either of those right now.

In the future (with #162), `awscli` won't be installed unless someone indicates their data is on s3 so this would be less common.
