### ISSUE TITLE
Generalize to other storage services

### ISSUE THREAD

**Issue by omri374** [drivendata/cookiecutter-data-science#213]
This repo is plain awesome. One suggestion I have is to allow a user to define the storage account in use (and remove depenency on s3 or aws). Many people don't have aws accounts and are working with other cloud providers or on-premises. 

Is the dependency on the aws Python package and s3 connectivity really mandatory for using this tool? Should it should be some kind of extension?

EDIT: I see that this is actually taken care of in #162. Cool! What's keeping this PR from being merged?

**Comment by pjbull** [comment]
Yep, this is planned in #162.

That PR needs working since the tests aren't passing yet, particularly on Windows (see #205, which is going in to that branch if you want a head start there).

Also, there aren't tests yet for each of the particular providers which need manual testing then mocks to make sure those functions work across providers and OSes.

Would love contributions there!

**Comment by pjbull** [comment]
Closing this issue since those items are covered elsewhere.
