### ISSUE TITLE
Add 'pip install -e .' in Makefile

### ISSUE THREAD

**Issue by cccntu** [drivendata/cookiecutter-data-science#237]
Hello, I just discovered this repo and it looks great!
I read the blog post: https://drivendata.github.io/cookiecutter-data-science/

And I am wondering if some of the mentioned commands should be in the Makefile, like:
`pip install -e .`
`pip freeze > requirements.txt`

**Comment by pjbull** [comment]
Local package is already installed with `make requirements`:
https://github.com/drivendata/cookiecutter-data-science/blob/0113a4ab1e926613abc7b48291a365819602c6a3/%7B%7B%20cookiecutter.repo_name%20%7D%7D/requirements.txt#L1-L2

We don't recommend using pip freeze to generate `requirements.txt` by default. Since it pins all installed packages, you'll never pick up updates/security fixes for those packages. We recommend just specifying the minimal set of packages + versions that you explicitly need in your project and letting the dependency resolver handle the rest.
