### ISSUE TITLE
Jupyter notebooks can’t get data at ../../data

### ISSUE THREAD

**Issue by mraarone** [drivendata/cookiecutter-data-science#279]
When I run jupyter on a notebook in the notebooks folder, it won’t let me access the data in the ../data folder. How is this usually done?

**Comment by pjbull** [comment]
Hi @mraarone, when you file an issue please include what you tried and the actual errors that you see.

Depending on what you're doing and how you're accessing files, you may need to run the jupyter server from the project root directory rather than the notebook folder.

Programmatically, your python code will be able to access anything your user has access to. For example:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/1799186/186722904-03e69e33-c867-42a8-99fc-4ea07ab47284.png">

Jupyter cannot _serve_ any content above the directory it is started in (e.g., see this issue https://github.com/jupyter/notebook/issues/230 )
