### ISSUE TITLE
Cookiecutter is now in Conda Forge

### ISSUE THREAD

**Issue by pydanny** [drivendata/cookiecutter-data-science#31]
This works for installation, so you might want to change your creation process to something like :

``` bash
$ conda config --add channels conda-forge
$ conda install cookiecutter
```

**Comment by pjbull** [comment]
Thanks @pydanny, is there an advantage to installing cookiecutter with conda? In this case `pip` seems pretty effective since it is on most systems and `cookiecutter` doesn't need complicated dependencies/compilation. 

Happy to include the conda-forge option in the instructions, but just curious if there's an advantage I'm missing.

**Comment by pjbull** [comment]
Closed by 2d106de5e267a947e659474bc1c5c6cd8247d20e

**Comment by pydanny** [comment]
Sorry, I didn't see your response.

The reason for Conda as an installation option is that it makes it easier for Conda users, which is what a lot of data people use to maintain their dependencies.

**Comment by pjbull** [comment]
:+1: in the README now, thanks @pydanny!
