### ISSUE TITLE
Set .gitignore for the data directory

### ISSUE THREAD

**Issue by isms** [drivendata/cookiecutter-data-science#32]
Goal: keep the `data/` folder in the project template for illustrative reasons, but by default ignore its contents once the cookiecutter has been instantiated and turned into a git repo.

**Comment by ohenrik** [comment]
This seems to be already fixed a while back. If I'm not mistaken here?:
https://github.com/drivendata/cookiecutter-data-science/commit/9841cfa1b63d1be5ee5a130d2dae92b95344931a

Or i might misinterpret your question?

**Comment by pjbull** [comment]
Yep, looks to me like this is currently working as designed. Folders show up in newly created repository, but nothing inside the data folder gets tracked in git.

**Comment by yahiakala** [comment]
Currently, the data folder does not get tracked in git. I think it would be useful to track it in git (along with its subfolders) so that the user doesn't have to create the subfolders each time the repo is cloned. I have the following in my .gitignore file now:

# exclude data from source control by default
data/raw/*
data/interim/*
data/processed/*
data/external/*

# gitkeep files
!.gitkeep
