### ISSUE TITLE
Workflow for working with figures and reports

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [drivendata/cookiecutter-data-science#58]
I just started using this cookiecutter and I'm wondering how people are using this directory structure in order to generate figures and reports.

Here's what I'm doing currently:

- do analysis and generate interesting figure, save them to `/reports/figures/`
- write up final jupyter notebook report from within `/notebooks/reports/`, any reference to figures are going to be `../../reports/figures/fig.png`
- export the report as `report.html` and place in `/reports/`

The issue now, is that when I view the `report.html`, the figures don't have the proper path.  How are people getting around this?

**Comment by pjbull** [comment]
One workaround is to embed the image data itself in the notebook. Instead of referencing the images to display them, you can execute a code cell like the below. In this case the actual image data will get inlined into the exported HTML, so you don't have to send along the images with the HTML. Downside is that you have to regenerate the HTML if the source image changes.

```
from IPython.display import Image, display
display(Image(data='path_to_image.png'))
```

**Comment by ConstantinoSchillebeeckx** [comment]
Ah! Great, didn't realize you could display images with those functions.  Thanks!

**Comment by pjbull** [comment]
A short addition: you may consider adding a rule to the `Makefile` to generate your report, for example:

```
report:
     jupyter nbconvert --to html --execute --ExecutePreprocessor.kernel_name=python notebooks/my_notebook.ipynb --output reports/my_report.html
```

(Note: `--ExecutePreprocessor.kernel_name=python` may or may not be necessary depending on your versions of conda/nbconvert/ipython).

**Comment by ConstantinoSchillebeeckx** [comment]
Oh thanks! I'll definitely add that to my Makefile.

In case anyone else finds this, I ended up generating a symlink to `figures/` within my `notebooks` directory so that I would only be using Markdown to display the image.

**Comment by pjbull** [comment]
Ah, nice. That's probably the cleanest solution. 👍

**Comment by ConstantinoSchillebeeckx** [comment]
I've noticed that the [symlink I've got setup](https://github.com/ConstantinoSchillebeeckx/cookiecutter-data-science/blob/8b3b5f17d3443d4a57be659d83086ff3ada4db3a/%7B%7Bcookiecutter.repo_name%7D%7D/notebooks/reports/figures) is being turned into a proper directory (not a symlink) when using cookiecutter.  Any idea why?

**Comment by isms** [comment]
@ConstantinoSchillebeeckx I'm wondering if you need to remove the symlink from the project and let that happen in your [post_gen](https://github.com/ConstantinoSchillebeeckx/cookiecutter-data-science/blob/master/hooks/post_gen_project.py#L24).

If the symlink already exists, is it plausible that cookiecutter might just copy that whole pointed-to directory because it's following the symlink?

**Comment by ConstantinoSchillebeeckx** [comment]
Looks like you found my work around; it just feels "ugly" :(

**Comment by pjbull** [comment]
Yeah, I did some poking and this is an issue with `cookiecutter`. I'm taking a quick look at the complexity of an upstream fix, but it will need a workaround for now...
