### ISSUE TITLE
Add the installation folder to .env

### ISSUE THREAD

**Issue by PetitLepton** [drivendata/cookiecutter-data-science#65]
Hi,

I am just starting to use the project. I noticed that most of the commands have relative paths like in the `Makefile`.

It is sometimes useful to have access to the full path. For example, when running cron jobs on some of the scripts inside the projects, getting the proper relative paths may be a bit tricky. One can use something like `os.path.abspath(__file__)` in the script to find the path but I thought that it would be easier if the project folder was dumped in the `.env`, the environment variable being then used for paths to the data or visualization folders.

Thanks.

**Comment by isms** [comment]
@PetitLepton Agree that relative paths are sometimes painful. However, instead of keeping this in `.env` (where you'd have to keep it updated), found a helpful [StackOverflow answer](http://stackoverflow.com/a/23324703) that does this programatically within the `Makefile`.

Does commit 5cc3192 solve this issue for you, now that the `Makefile` provides a variable `PROJECT_DIR` with the absolute path?

**Comment by PetitLepton** [comment]
@isms This is very useful. I can use this with a new rule on the `Makefile` to add it dynamically. Thank you.
