### ISSUE TITLE
Syncing data with the cloud as a git hook

### ISSUE THREAD

**Issue by drorata** [drivendata/cookiecutter-data-science#82]
Disclaimer: I haven't really used cookiecutter-data-science (and no other cutter). I'm still evaluating this.

Having the data syncing with the cloud (S3) being part of the `Makefile` is harder to enforce as part of a workflow. Users would have to remember to push data changes to the cloud. Would it make sense/did you consider to use git hooks? For example sync the data directory upon push.

**Comment by pjbull** [comment]
git hooks are a great tool that we often use for things like this. 

I'd love to see the option for git hooks (including flake8 or running test in addition to syncing data. However, it doesn't make sense to make this the default since we don't enforce a particular VCS in the default project (and probably won't).

When we have better support for forking paths in the project initial setup, we should revisit this.

**Comment by drorata** [comment]
It is a tricky game of balance between how restrictive you want to be (conda? git?) and what additional features can be supported. Specifically, I would argue that git is nowadays a standard, and almost by design anyone using cookiecutter uses git. So I wouldn't say it is such a harsh enforcement.

**Comment by pjbull** [comment]
Possibly true, but until we can better support forking paths on cookiecutter we won't single out a VCS. Here's the issue tracking that:

https://github.com/drivendata/cookiecutter-data-science/issues/56#issuecomment-277765734

**Comment by isms** [comment]
Closing/does not seem to have sparked a lot of discussion and could be implement as one line in `.git/hooks/post-commit`
