### ISSUE TITLE
Common utility functions for data science projects

### ISSUE THREAD

**Issue by noahstier** [drivendata/cookiecutter-data-science#89]
This is a handy decorator I use for caching the intermediate results of data processing pipelines. Does this kind of utility belong in cookiecutter-data-science? If so I'll make a PR, and regardless I'd be curious to see what other handy snippets people use.

https://github.com/noahstier/cookiecutter-data-science/blob/add_cache_util/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/utils/decorators.py

```python
'''
example: cache the result of an expensive data loading operation

Loading several gigabytes of video from hundreds of files is slow,
but reading that same data from a single pickle file is faster.
'''

import skvideo.io
import numpy as np

project_dir = '/home/project'
cache_dir = os.path.join(project_dir, 'data', 'cache')
videos_dir = os.path.join(project_dir, 'data', 'processed', 'videos')
video_extensions = {'.mp4', '.avi', '.mov'}

@cache(os.path.join(project_dir, 'data', 'cache'))
def load_videos(direc, grayscale=False):

    video_files = []
    for dirname, dirnames, filenames in os.path.walk(direc):
        video_files.extend([os.path.join(dirname, f) for f in filenames
                            if f in video_extensions])

    return np.array([skvideo.io.vread(f, as_grey=grayscale) for f in filenames])


# use the function with different arguments
videos = load_videos(videos_dir, grayscale=False, cache_file='trainmodel1')
videos = load_videos(videos_dir, grayscale=True, cache_file='trainmodel2')

# see all the cached result files for this function
videos.cache_files()

# delete all the cached result files for this functin
videos.clear_cache_files()
```

And I should add that the reasons for using this over functools.lru_cache are 1. that you can't pass numpy arrays to lru_cache and 2. lru_cache is in-memory only

**Comment by epogrebnyak** [comment]
Can you please elaborate what is your motibation todo caching and opposed to processing and atoring the results? Data size?

**Comment by noahstier** [comment]
This is processing and storing the results, in pickle files.

It's a convenient way to store the result of any expensive processing operation. For example let's say you have a script that starts by computing optical flow on a bunch of videos. Adding one `@cache` line is enough to store the results without cluttering your code with all kinds of os.path calls, etc.

**Comment by isms** [comment]
@noahstier I really like the example but I think we want to avoid anything that feels like domain-specific clutter. Judging by where we see people using this (even R users, to some extent), it makes sense to us to keep a strict separation of concerns between structure and contents.

That being said it would probably be a cool project to curate a repo of useful data science snippets - if you are interested in doing that we'd love to be kept updated.

**Comment by elgehelge** [comment]
This is great. I've been using `functools.lru_cache` but I had to limit the way I used it because it did not work for numpy arrays. Thanks for sharing.

To add to the discussion, why was I using caching?: I was using caching because I had a very large dataset split among multiple files. When running my notebooks I wanted to to load only a subset of the data, which would vary. In one cell I wanted 100K ellement, and in the next I wanted 150K, But loading everything would be impossible. So I made a generator that cached the data being streamed in. So when loading in 150K I would already have 100K in memory. So, all in all a very narrow use case. I think this project should be as minimal as possible. But I would be great to have a library of useful utility functions!
